use_frameworks!

platform :ios, '8.0'

target 'HBObjectiveCMacro_Example' do
  pod 'HBObjectiveCMacro', :path => '../'

  target 'HBObjectiveCMacro_Tests' do
    inherit! :search_paths

    
  end
end
